FROM ghcr.io/railwayapp-templates/postgres-ssl:16

RUN apt-get update && apt-get install -y \
    postgresql-16-cron

RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample
RUN echo "cron.database_name = 'railway'" >> /usr/share/postgresql/postgresql.conf.sample
